### ISSUE TITLE
Вопросы по скрипту translate.ps1

### ISSUE THREAD

**Issue by ipwin-github** [FOSWLY/vot-cli#1]
Я использую скрипт translate.ps1 из архива vot-cli для скачивания видео с переведенным звуком. Возникли пару вопросов по использованию этого скрипта. По умолчанию скрипт скачивает все видео в формате webm и в максимально доступном разрешении, например 2160p60. 
Вопрос, можно ли получить переведённое видео в другом формате, например mp4 ? И главное, можно ли ограничить максимально доступное качество скачиваемого видео, например что-бы качалось максимум 1080p60 ?

**Comment by ilyhalight** [comment]
Можно. [Документация yt-dlp](https://github.com/yt-dlp/yt-dlp#format-selection) вам в помощь. Я примерно набросал пару вариантов, что будут скачивать видео в максимальном разрешение до 1080p, и тоже самое, но уже в формате mp4. За работоспособность не ручаюсь.

Загрузка видео в формате mp4 в максимальном качестве:
`yt-dlp --format "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b" -o $temp_video $video_link`

Загрузка видео в формате mp4 в максимальном качестве до 1080p (включительно)
`yt-dlp --format "bv*[ext=mp4][height<=1080]+ba[ext=m4a]/b[ext=mp4][height<=1080] / bv*+ba/b" -o $temp_video $video_link`

Иногда аудио не удается скачать и yt-dlp возвращает 403 forbidden, возможно, это проблема в том, что у меня старая версия yt-dlp. Тут уже сами потестируйте.

Чтобы поменять формат вам нужно отредактировать текст в 22 строчке: `yt-dlp -o $temp_video $video_link` на одну из выше приведенных строчек или на ту, что вы сами составите

**Comment by ipwin-github** [comment]
Все работает, отредактировал строку 22 и теперь видео скачивается в формате mp4 и в качестве максимум 1080p60. Ошибки 403 forbidden у меня еще не разу не было. Спасибо!
