### ISSUE TITLE
Проблемы с запуском.

### ISSUE THREAD

**Issue by SpbskvA** [FOSWLY/vot-cli#13]
Здравствуйте, пробовал на WSL и Ubuntu, выходила одинаковая ошибка, пробывал несколько раз переустановливать разными способами.

`andrey@LAPTOP-3UTGFQOS:~/prods/tg_bot$ sudo vot-cli --help
file:///usr/local/lib/node_modules/vot-cli/src/index.js:127
        let subtitles = subtitlesResponse.subtitles ?? [];
                                                     ^
SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)`
    Вообще не могу понять почему так происходит. Можете пожалуйста подсказать с чем это может быть связано?

**Comment by ilyhalight** [comment]
Какую версию NodeJS вы используете?

**Comment by SpbskvA** [comment]
Спасибо, буквально два часа назад сам догадался). (Использовал 12ю оказывается)
