### ISSUE TITLE
Добавить поддержку сервиса.

### ISSUE THREAD

**Issue by stemplock** [FOSWLY/vot-cli#18]
Добрый день. Есть возможность добавить поддержку Google Drive?
Или это у меня не работает.

Пример ссылки:
https://drive.google.com/file/d/1Md7mH5takfZ6YR-NgEBbh3sDHn6pmH4W/view?usp=drivesdk

**Comment by ilyhalight** [comment]
Позже добавлю

**Comment by stemplock** [comment]
В течении недели стоит ждать или пока на браузере запилить?)

**Comment by stemplock** [comment]
Еще аргумент для установки имени файла было бы класно.

**Comment by ilyhalight** [comment]
> В течении недели стоит ждать или пока на браузере запилить?)

В течение часа может будет, там нужно, только, перенести из основного скрипта

**Comment by ilyhalight** [comment]
Добавил

> поддержку Google Drive

> аргумент для установки имени файла
