### ISSUE TITLE
Скрипт сломался?

### ISSUE THREAD

**Issue by 31normaslavik** [FOSWLY/vot-cli#19]
`vot-cli --output="." "https://youtu.be/-I26usMiuS4?si=jWfl-FJAW-tQb1-T"
(node:30941) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
⚠ Translating finished! (ID: -I26usMiuS4).
  ✔ Forming a link to the video
  ✔ Failed to request video translation
  ✖ Downloading failed! Link "Failed to request video translation" not found
  ✔ Finish (ID: -I26usMiuS4).

AxiosError: Request failed with status code 400
    at settle (file:///usr/lib/node_modules/vot-cli/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///usr/lib/node_modules/vot-cli/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///usr/lib/node_modules/vot-cli/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async yandexRawRequest (file:///usr/lib/node_modules/vot-cli/src/yandexRawRequest.js:13:3)
    at async Object.requestVideoTranslation (file:///usr/lib/node_modules/vot-cli/src/yandexRequests.js:28:5)
    at async translateVideo (file:///usr/lib/node_modules/vot-cli/src/translateVideo.js:14:3)
    at async translate (file:///usr/lib/node_modules/vot-cli/src/index.js:93:5)
    at async file:///usr/lib/node_modules/vot-cli/src/index.js:281:32 {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/x-protobuf',
      'Content-Type': 'application/x-protobuf',
      'Accept-Language': 'en',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36',
      Pragma: 'no-cache',
      'Cache-Control': 'no-cache',
      'Sec-Fetch-Mode': 'no-cors',
      'sec-ch-ua': null,
      'sec-ch-ua-mobile': null,
      'sec-ch-ua-platform': null,
      'Vtrans-Signature': '8c0e27e9a596f4619312e277d2a44317b4c8bf1f15665e25cb500f44ef493a0c',
      'Sec-Vtrans-Token': 'D098369F22B146FFA00D349787ECD227',
      'Content-Length': '63',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: 'https://api.browser.yandex.ru/video-translation/translate',
    method: 'post',
    proxy: false,
    responseType: 'arraybuffer',
    data: <Buffer 1a 1c 68 74 74 70 73 3a 2f 2f 79 6f 75 74 75 2e 62 65 2f 2d 49 32 36 75 73 4d 69 75 53 34 28 01 31 00 00 00 00 00 50 75 40 38 01 42 02 65 6e 48 00 50 ... 13 more bytes>
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '63',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    _header: 'POST /video-translation/translate HTTP/1.1\r\n' +
      'Accept: application/x-protobuf\r\n' +
      'Content-Type: application/x-protobuf\r\n' +
      'Accept-Language: en\r\n' +
      'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36\r\n' +
      'Pragma: no-cache\r\n' +
      'Cache-Control: no-cache\r\n' +
      'Sec-Fetch-Mode: no-cors\r\n' +
      'Vtrans-Signature: 8c0e27e9a596f4619312e277d2a44317b4c8bf1f15665e25cb500f44ef493a0c\r\n' +
      'Sec-Vtrans-Token: D098369F22B146FFA00D349787ECD227\r\n' +
      'Content-Length: 63\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: api.browser.yandex.ru\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/video-translation/translate',
    _ended: true,
    res: IncomingMessage {
      _events: [Object],
      _readableState: [ReadableState],
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      _eventsCount: 4,
      responseUrl: 'https://api.browser.yandex.ru/video-translation/translate',
      redirects: [],
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 16,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.browser.yandex.ru',
    protocol: 'https:',
    _redirectable: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 63,
      _requestBodyBuffers: [],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.browser.yandex.ru/video-translation/translate',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kChunkedBuffer)]: [],
    [Symbol(kChunkedLength)]: 0,
    [Symbol(kSocket)]: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.browser.yandex.ru',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.browser.yandex.ru',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _writableState: [WritableState],
      allowHalfOpen: false,
      _maxListeners: undefined,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      timeout: 5000,
      parser: null,
      _httpMessage: null,
      autoSelectFamilyAttemptedAddresses: [Array],
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: -1,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 749,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 564,
        [Symbol(triggerId)]: 562
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 1,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'accept-language': [Array],
      'user-agent': [Array],
      pragma: [Array],
      'cache-control': [Array],
      'sec-fetch-mode': [Array],
      'vtrans-signature': [Array],
      'sec-vtrans-token': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: Object [AxiosHeaders] {
      'content-length': '87',
      'content-type': 'text/plain; charset=utf-8',
      date: 'Wed, 22 May 2024 17:00:27 GMT',
      'set-cookie': [Array],
      'x-yandex-req-id': '1716397227676096-52189200750501918-w64d23wgxvgjdrjq-BAL'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      url: 'https://api.browser.yandex.ru/video-translation/translate',
      method: 'post',
      proxy: false,
      responseType: 'arraybuffer',
      data: <Buffer 1a 1c 68 74 74 70 73 3a 2f 2f 79 6f 75 74 75 2e 62 65 2f 2d 49 32 36 75 73 4d 69 75 53 34 28 01 31 00 00 00 00 00 50 75 40 38 01 42 02 65 6e 48 00 50 ... 13 more bytes>
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '63',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      _header: 'POST /video-translation/translate HTTP/1.1\r\n' +
        'Accept: application/x-protobuf\r\n' +
        'Content-Type: application/x-protobuf\r\n' +
        'Accept-Language: en\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36\r\n' +
        'Pragma: no-cache\r\n' +
        'Cache-Control: no-cache\r\n' +
        'Sec-Fetch-Mode: no-cors\r\n' +
        'Vtrans-Signature: 8c0e27e9a596f4619312e277d2a44317b4c8bf1f15665e25cb500f44ef493a0c\r\n' +
        'Sec-Vtrans-Token: D098369F22B146FFA00D349787ECD227\r\n' +
        'Content-Length: 63\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.browser.yandex.ru\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/video-translation/translate',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.browser.yandex.ru',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [TLSSocket],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: <Buffer 28 65 72 72 6f 72 5f 69 64 3a 31 37 31 36 33 39 37 32 32 37 36 37 36 30 39 36 2d 35 32 31 38 39 32 30 30 37 35 30 35 30 31 39 31 38 2d 77 36 34 64 32 ... 37 more bytes>
  }
}
`

**Comment by rorshek** [comment]
+, у меня тоже не работает, ждем обновления

**Comment by ilyhalight** [comment]
Обновитесь до 1.4.1
