### ISSUE TITLE
Entered Unsupported link

### ISSUE THREAD

**Issue by Act0r1** [FOSWLY/vot-cli#2]
Пишу в терминал: vot-cli --outpath="./" https://www.youtube.com/watch\?v\=Y_IQ7UttNUM\&t\=14s  

Получаю перевод, как ссылку, то есть можно перейти и слушать, но оно никак не сохраняет ее в аудиофайл, если сделать так:

vot-cli --outpath="./" "https://www.youtube.com/watch\?v\=Y_IQ7UttNUM\&t\=14s" - получаю entered unsupported link

**Comment by ilyhalight** [comment]
слэши лишние, скорее всего из-за них не сохраняет/не переводит

**Comment by ilyhalight** [comment]
> outpath

Нужно писать не `outpath=...`, а `output=...` для сохранения

**Comment by Act0r1** [comment]
> > outpath
> 
> Нужно писать не `outpath=...`, а `output=...` для сохранения

вот блин, не заметил, спасибо)
