### ISSUE TITLE
Зависания, долгая загрузка

### ISSUE THREAD

**Issue by 31normaslavik** [FOSWLY/vot-cli#20]
Включённый debug выдает много спама в консоль (../lib/node_modules/vot-cli/src/config/config.js)
Загрузка перевода стала на порядок дольше чем было в 1.4.0
vot-cli не возвращает код ошибки, а результат работы всегда 0. Не критично, но было бы неплохо получать хотя бы 1 в случае ошибки
На ссылке [тык](https://www.youtube.com/watch?v=TMMcXsp4LaU) vot-cli так вообще завис на вечность, заблокировав поток
До этого завис на ссылке [тык](https://www.youtube.com/watch?v=-T0MGehwWvE)
проблема может быть и с моей стороны, этого не исключаю

**Comment by ilyhalight** [comment]
Кроме обновления ключа ничего не менялось в 1.4.1, скорее всего, проблема на вашей стороне. По поводу того, что стало дольше, возможно, сервера яндекса сейчас сильнее нагружены

**Comment by 31normaslavik** [comment]
> Кроме обновления ключа ничего не менялось в 1.4.1, скорее всего, проблема на вашей стороне. По поводу того, что стало дольше, возможно, сервера яндекса сейчас сильнее нагружены

Согласен. Сейчас проверил на массиве ссылок и без проблем все переводы скачались
