### ISSUE TITLE
Помогите собрать для WINDOWS

### ISSUE THREAD

**Issue by InfernalWolf666** [FOSWLY/vot-cli#23]
Ребята я понимаю что Вы профессианалы во всяких ковыряниях.
Я не могу собрать для Windows , я читаю Вашу инструкцию но она поверхностная!

Сделана реально на отьебись!

Я следую шагам, я спотыкаюсь на установке vot-Cli 

Чёрт подери, я его распоковал, Nodejs его не подхватывает, естественно я как думаю что эти файлы нужно просто закинуть в нужную папку , но какую , у вас нет конкретики !

Просто либо снимите видео на ютуб, не все грамотные программеры, я обычный человек, который всё больше и больше начинает ненавидеть гит хаб, потому что здесь умные люди, но вы настолько умны, что вас начинающие не понимают

**Comment by R2008KK** [comment]
У кого проблемы с установкой просто вручную перейдите в npm\node_modules\vot-cli\node_modules\.bin или подобное, и запускайте vot-cli.cmd
(Под проблемами с установкой я имею в виду то, что по каким-то причинам npm не устанавливает проект глобально, а потому на команду "vot-cli ..." в командной строке тебе скажет, что такого файла не существует)
