### ISSUE TITLE
Изменить имя выходного файла после скачивания

### ISSUE THREAD

**Issue by DmitriyBatkovich** [FOSWLY/vot-cli#25]
Есть возможность у этой штуки поставить флаг когда файл скачается чтобы он назвался так как я этого захочу а не рандомный набор символов который есть сейчас?

**Comment by ilyhalight** [comment]
![изображение](https://github.com/FOSWLY/vot-cli/assets/62353659/9f821428-fe45-4695-b193-15971e2b0df3)

**Comment by DmitriyBatkovich** [comment]
Понял спасибо
