### ISSUE TITLE
Можно ли сделать чтобы vot-cli мог обрабатывать файлы с локального пк, не по ссылкам?

### ISSUE THREAD

**Issue by DmitriyBatkovich** [FOSWLY/vot-cli#26]
Можно ли сделать чтобы vot-cli мог обрабатывать файлы с локального пк, не по ссылкам?

**Comment by ilyhalight** [comment]
Нельзя, максимум, можете сделать для себя какой-нибудь автозаливщик на тот же яндекс/гугл/ютуб/что-то подобное и совместить это с vot-cli
