### ISSUE TITLE
Почему то не работает через туннель serveo.net

### ISSUE THREAD

**Issue by DmitriyBatkovich** [FOSWLY/vot-cli#27]
C:\Users\KsiJa>vot-cli --output="." "https://71e7b3400d8e1e8f938cfe49b6e4f68f.serveo.net/book.mp4"
getVideoID custom https://71e7b3400d8e1e8f938cfe49b6e4f68f.serveo.net/book.mp4
‼ Translating finished! (ID: https://71e7b3400d8e1e8f938cfe49b6e4f68f.serveo.net/book.mp4).
  √ Forming a link to the video
  √ Failed to request video translation
  × Downloading failed! Link "Failed to request video translation" not found
  √ Finish (ID: https://71e7b3400d8e1e8f938cfe49b6e4f68f.serveo.net/book.mp4).

requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (?0:        276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (!0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  (0
:       276479903
requestVideoTranslation
yandexRequest: /video-translation/translate
yandexRequest: 200  :   276479903JVВозникла ошибка при переводе, попробуйте позже
Error: Возникла ошибка при переводе, попробуйте позже
    at file:///C:/Users/KsiJa/AppData/Roaming/npm/node_modules/vot-cli/src/index.js:120:17
    at file:///C:/Users/KsiJa/AppData/Roaming/npm/node_modules/vot-cli/src/translateVideo.js:31:11
    at file:///C:/Users/KsiJa/AppData/Roaming/npm/node_modules/vot-cli/src/yandexRawRequest.js:37:7
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async yandexRawRequest (file:///C:/Users/KsiJa/AppData/Roaming/npm/node_modules/vot-cli/src/yandexRawRequest.js:13:3)
    at async Object.requestVideoTranslation (file:///C:/Users/KsiJa/AppData/Roaming/npm/node_modules/vot-cli/src/yandexRequests.js:28:5)
    at async translateVideo (file:///C:/Users/KsiJa/AppData/Roaming/npm/node_modules/vot-cli/src/translateVideo.js:14:3)
    at async translate (file:///C:/Users/KsiJa/AppData/Roaming/npm/node_modules/vot-cli/src/index.js:93:5)
    at async Timeout._onTimeout (file:///C:/Users/KsiJa/AppData/Roaming/npm/node_modules/vot-cli/src/index.js:287:38)

**Comment by DmitriyBatkovich** [comment]
Кастомные сервисы он поддерживает однако заливать на них такие большие файлы по 100 метров долго туннель работает в браузере начинает загрузку файла, но здесь почему-то он начинает переводить и падает по итогу, даже если изменить тип работы туннеля чтобы видео в браузере показывалось

**Comment by DmitriyBatkovich** [comment]
Может ему над какие-то заголовки отдавать или ещё что-то?

**Comment by DmitriyBatkovich** [comment]
Файл по длине который поддерживает переводчик до 4 часов 3 часа 50 минут если его залить на тот же dropbox то vot-cli его спокойно переводить но заливать долго

**Comment by DmitriyBatkovich** [comment]
Вообщем сейчас проверил на 10 минутном файле он его перевёл значит буду тогда резать файлы на более меньшее время осталось только найти то время с которым он способен нормально переводить, хотя кнш это странно что файл на 3 часа 50 минут залиты на dropbox он нормально переводит а через туннель уже нет.

**Comment by DmitriyBatkovich** [comment]
Вообщем через туннель он может максимум 50 минут переводить ну ладно будет так тогда работать

**Comment by ilyhalight** [comment]
> Вообщем сейчас проверил на 10 минутном файле доступном через туннель он его перевёл значит буду тогда резать файлы на более меньшее время осталось только найти то время с которым он способен нормально переводить, хотя кнш это странно что файл на 3 часа 50 минут залиты на dropbox он нормально переводит а через туннель уже нет.

Неизвестно с чем это связано, такое же поведение и с гугл диском

**Comment by DmitriyBatkovich** [comment]
> > Вообщем сейчас проверил на 10 минутном файле доступном через туннель он его перевёл значит буду тогда резать файлы на более меньшее время осталось только найти то время с которым он способен нормально переводить, хотя кнш это странно что файл на 3 часа 50 минут залиты на dropbox он нормально переводит а через туннель уже нет.
> 
> Неизвестно с чем это связано, такое же поведение и с гугл диском

Ну значит поход придётся ещё и свой vot-cli писать ну ладно пока он по 50 минут справляется переводить хотя иногда падает, я так пон из-за каких то timeout'ов

**Comment by ilyhalight** [comment]
> > > Вообщем сейчас проверил на 10 минутном файле доступном через туннель он его перевёл значит буду тогда резать файлы на более меньшее время осталось только найти то время с которым он способен нормально переводить, хотя кнш это странно что файл на 3 часа 50 минут залиты на dropbox он нормально переводит а через туннель уже нет.
> > 
> > 
> > Неизвестно с чем это связано, такое же поведение и с гугл диском
> 
> Ну значит поход придётся ещё и свой vot-cli писать ну ладно пока он по 50 минут справляется переводить хотя иногда падает, я так пон из-за каких то timeout'ов



> > > Вообщем сейчас проверил на 10 минутном файле доступном через туннель он его перевёл значит буду тогда резать файлы на более меньшее время осталось только найти то время с которым он способен нормально переводить, хотя кнш это странно что файл на 3 часа 50 минут залиты на dropbox он нормально переводит а через туннель уже нет.
> > 
> > 
> > Неизвестно с чем это связано, такое же поведение и с гугл диском
> 
> Ну значит поход придётся ещё и свой vot-cli писать ну ладно пока он по 50 минут справляется переводить хотя иногда падает, я так пон из-за каких то timeout'ов

Именно апи яндекса почему-то выдает ошибку, а не сам cli

**Comment by DmitriyBatkovich** [comment]
> > > > Вообщем сейчас проверил на 10 минутном файле доступном через туннель он его перевёл значит буду тогда резать файлы на более меньшее время осталось только найти то время с которым он способен нормально переводить, хотя кнш это странно что файл на 3 часа 50 минут залиты на dropbox он нормально переводит а через туннель уже нет.
> > > 
> > > 
> > > Неизвестно с чем это связано, такое же поведение и с гугл диском
> > 
> > 
> > Ну значит поход придётся ещё и свой vot-cli писать ну ладно пока он по 50 минут справляется переводить хотя иногда падает, я так пон из-за каких то timeout'ов
> 
> > > > Вообщем сейчас проверил на 10 минутном файле доступном через туннель он его перевёл значит буду тогда резать файлы на более меньшее время осталось только найти то время с которым он способен нормально переводить, хотя кнш это странно что файл на 3 часа 50 минут залиты на dropbox он нормально переводит а через туннель уже нет.
> > > 
> > > 
> > > Неизвестно с чем это связано, такое же поведение и с гугл диском
> > 
> > 
> > Ну значит поход придётся ещё и свой vot-cli писать ну ладно пока он по 50 минут справляется переводить хотя иногда падает, я так пон из-за каких то timeout'ов
> 
> Именно апи яндекса выдает ошибку, а не сам cli



> > > > Вообщем сейчас проверил на 10 минутном файле доступном через туннель он его перевёл значит буду тогда резать файлы на более меньшее время осталось только найти то время с которым он способен нормально переводить, хотя кнш это странно что файл на 3 часа 50 минут залиты на dropbox он нормально переводит а через туннель уже нет.
> > > 
> > > 
> > > Неизвестно с чем это связано, такое же поведение и с гугл диском
> > 
> > 
> > Ну значит поход придётся ещё и свой vot-cli писать ну ладно пока он по 50 минут справляется переводить хотя иногда падает, я так пон из-за каких то timeout'ов
> 
> > > > Вообщем сейчас проверил на 10 минутном файле доступном через туннель он его перевёл значит буду тогда резать файлы на более меньшее время осталось только найти то время с которым он способен нормально переводить, хотя кнш это странно что файл на 3 часа 50 минут залиты на dropbox он нормально переводит а через туннель уже нет.
> > > 
> > > 
> > > Неизвестно с чем это связано, такое же поведение и с гугл диском
> > 
> > 
> > Ну значит поход придётся ещё и свой vot-cli писать ну ладно пока он по 50 минут справляется переводить хотя иногда падает, я так пон из-за каких то timeout'ов
> 
> Именно апи яндекса выдает ошибку, а не сам cli

Ну это я понимаю что проблема со стороны яндекса, вот сейчас думаю на питоне чот подобное навасянить если он так и будет часто падать
