### ISSUE TITLE
Азиатка сломала скрипт!

### ISSUE THREAD

**Issue by InfernalWolf666** [FOSWLY/vot-cli#29]
Снова привет, спасибо что мне помогали разобраться 

вообщем странная проблема, Азиаточка ломает скрипт, до этого всё работало, причем и на других видео всё работает, НО именно азиатка ломает скрипт 

Вот когда у меня уже всё настроено я ввожу

`.\translate.ps1 "https://youtu.be/AP7hAHJNEWw?si=ActQE5Se7F7vlvK3"`

и вижу вот такую картину 
![Снимок экрана 2024-06-25 040720](https://github.com/FOSWLY/vot-cli/assets/67106758/58973bdb-ac7a-4b95-bce5-dd1d743caab8)

хотя до этого всё работало и работает на других видео, что я снова делаю не так?

**Comment by InfernalWolf666** [comment]
Аааау, ну ребята, есть кто живой?!

**Comment by InfernalWolf666** [comment]
я просто тоже времени не терял, воспользовался командой 
`vot-cli --input чтото там аудио "ССЫЛОЧКА на азиатку"`

и да, скачался mp3 файл, но он весит 0 кб , и не воспроизводится, тоесть чтото не так , но что именно поих познаний не хватает , хотя до этого перевод качался и обьединялся с видео.

**Comment by ilyhalight** [comment]
> и да, скачался mp3 файл, но он весит 0 кб , и не воспроизводится, тоесть чтото не так , но что именно поих познаний не хватает , хотя до этого перевод качался и обьединялся с видео.

Яндекс шалит, он на этом видео почему-то выдает невалидную ссылку на аудио файл. Надо поставить язык на корейский (`vot-cli --lang="ko"`) и выдаст нормальную ссылку на аудио файл

В translate.ps1 к сожалению нельзя задать язык

**Comment by InfernalWolf666** [comment]
> > и да, скачался mp3 файл, но он весит 0 кб, и не воспроизводится, тоесть чтото не так, но чего именно поих познаний не хватает, хотя до этого перевода качался и обьединялся с видео.
> 
> Яндекс шалит, он на этом видео почему-то выдает недействительную ссылку на аудиофайл. Надо поставить корейский язык ( `vot-cli --lang="ko"`) и выдаст нормальную ссылку на аудиофайл
> 
> В translate.ps1 к сожалению нельзя задать язык

да да я пробовал язык ставить , тоже выпендривается

**Comment by InfernalWolf666** [comment]
хах, странный прикол обнаружил, смотрел сейчас гайд в Tekken 8 , и видео не может быть переведено, открыл яндекс браузер, и он говорит что невозможно перевести видео формат аудио не поддерживается

**Comment by InfernalWolf666** [comment]
проблема замечена в этом видео [https://youtu.be/dsFWG-oKZ8o?si=AhEKSk8hBiWl_hz1](url)

**Comment by ilyhalight** [comment]
> проблема замечена в этом видео [https://youtu.be/dsFWG-oKZ8o?si=AhEKSk8hBiWl_hz1](url)

тут тоже яндекс отдает невалидную ссылку, лечится сменой языка на авто

**Comment by InfernalWolf666** [comment]
всё, понял что сама нейронка яндекса косячит, я закрою тему что бы глаза не мусолила
