### ISSUE TITLE
why translation into Chinese is not supported

### ISSUE THREAD

**Issue by xixino** [FOSWLY/vot-cli#5]
Thank you for everything, I wonder why translation into Chinese is not supported
`D:\vot-cli>vot-cli --output=vot-cli --reslang=zh https://www.youtube.com/watch?v=GWGbOjlJDkU&t=23s
Response language is set to zh
‼ Translating finished! (ID: GWGbOjlJDkU).
  √ Forming a link to the video
  √ Failed to request video translation
  × Downloading failed! Link "Failed to request video translation" not found
  √ Finish (ID: GWGbOjlJDkU).
't' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by ilyhalight** [comment]
error on the yandex side
