### ISSUE TITLE
Скачивание субтитров

### ISSUE THREAD

**Issue by m-danya** [FOSWLY/vot-cli#6]
Как я понял, в оригинальное расширение (https://github.com/ilyhalight/voice-over-translation)  недавно научилось получать от Яндекса субтитры, переведённые на нужный язык: https://github.com/ilyhalight/voice-over-translation/issues/352.

Очень хотелось бы иметь возможность получать такой файлик с субтитрами и в консольной версии 😃 (в каком-нибудь стандартном виде типа .srt  или хотя бы просто текстом с таймкодами)

p.s. желательно чтобы можно было скачать субтитры как оригинальные, так и переведенные

**Comment by ilyhalight** [comment]
Возможно, позже сделаю такую функцию

**Comment by ilyhalight** [comment]
Реализовано в 1.2

**Comment by it-spectre-ru** [comment]
подскажите почему при получении русских субтитров в файле набор символов? 
![image](https://github.com/FOSWLY/vot-cli/assets/32254365/c52ee320-5517-42fe-a776-5bde5a80eb82)

**Comment by ilyhalight** [comment]
> подскажите почему при получении русских субтитров в файле набор символов? ![image](https://private-user-images.githubusercontent.com/32254365/310547030-c52ee320-5517-42fe-a776-5bde5a80eb82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDIxMzQsIm5iZiI6MTcwOTc0MTgzNCwicGF0aCI6Ii8zMjI1NDM2NS8zMTA1NDcwMzAtYzUyZWUzMjAtNTUxNy00MmZlLWE3NzYtNWJkZTVhODBlYjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE2MTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhM2E4ODYxOTU1Yzg0MTE4NmM5OWYyODg0ZDkxNWJhZmZiODgzNDYwYTA4NjIzY2I1ZGNjNmNhNWYyOTM4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S-VYp-zYeCaQF2sNIIvYYos48j-3D0va-Rizt3BK1Eo)

это юникод, его можно перевести в обычный текст с помощью энкодеров, например https://checkserp.com/encode/unicode/
