### ISSUE TITLE
Расширение субтитров

### ISSUE THREAD

**Issue by zuccert** [FOSWLY/vot-cli#8]
Здравствуйте. Проблема в том что субтитры скачиваются в json. Есть ли какой нибудь конвертер для преобразования в .srt

**Comment by zuccert** [comment]
Не нашел нормальный конвертер. Вот тут сделал https://github.com/zuccert/json-to-srt

**Comment by OlegLxx** [comment]
Здравствуйте. Дабы не плодить новые issues, спрошу по поводу субтитров здесь: 
Возможно ли технически подсунуть поправленный файл с субтитрами, чтобы на его основе уже генерилась более корректная озвучка? Очень уж много косяков в автоматическом распознавании речи. Было бы классно.
