### ISSUE TITLE
Сколько хранятся видео на сервере yandex?

### ISSUE THREAD

**Issue by ennnnnne1** [FOSWLY/vot-cli#9]
Привет, может кто-нибудь знает или исследовал?
Сколько хранится перевод на серверах Яндекса?
Существуют ли какие-нибудь ограничения на перевод с 1 IP?

**Comment by ilyhalight** [comment]
Не знаю, сколько перевод хранится, скорее всего, это зависит от того, насколько часто к видео запрашивают перевод. Но ссылка живет 2 часа и после заново надо ее запрашивать
![изображение](https://github.com/FOSWLY/vot-cli/assets/62353659/f365fd4b-7346-490f-b404-2bfc2128a353)
